name: upm-release
description: A GitHub action to sign and release a Unity upm package.
branding:
  icon: gift
  color: blue
inputs:
  username:
    description: The username for the Unity account.
    required: true
  password:
    description: The password for the Unity account.
    required: true
  organization-id:
    description: The organization ID for the Unity account.
    required: true
  package-json:
    description: Path to the package.json file. Defaults to `**/Packages/**/package.json` glob search.
    required: false
  release-title:
    description: Optional title for the release.
    required: false
  release-notes:
    description: Optional release notes.
    required: false
  github-token:
    description: GitHub token to create releases and upload assets. Defaults to the GITHUB_TOKEN secret, but may be required if permissions are not set correctly or the repository is private.
    required: false
  split-upm-branch:
    description: Optional branch name if the package release tag should be pushed to a different branch than the default branch. Pass 'none' to disable the subtree split.
    required: false
    default: 'upm'
runs:
  using: node20
  main: dist/index.js
